version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.5.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Update yarn lockfile
          command: |
            # If the branch is a greenkeeper branch set env to empty string so lock file is updated
            # The following issue has more information around why this is needed https://github.com/greenkeeperio/greenkeeper-lockfile/issues/58
            if [[ $CIRCLE_BRANCH == greenkeeper* ]];
            then
              CI_PULL_REQUEST=""
            fi

            git config --global user.email "support@greenkeeper.io"
            git config --global user.name "greenkeeperio-bot"

            yarn run greenkeeper-lockfile-update

      - run: cd xstate-to-svg && yarn run lint
      - run: cd xstate-to-svg && yarn run test
      - run: cd xstate-to-svg && yarn run build

      - run: cd redux-saga-state-machine && yarn run lint
      - run: cd redux-saga-state-machine && yarn run test
      - run: cd redux-saga-state-machine && yarn run build

      - run: cd example && yarn run lint
      - run: cd example && yarn run test
      # - run: cd example && yarn run build

      - run:
          name: Upload yarn lockfile
          command: yarn run greenkeeper-lockfile-upload

      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

      - run:
          name: Configure Git
          command: |
            git config --global user.email "circleci@monket.net"
            git config --global user.name "circleci"

      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - run: yarn run publish

workflows:
  version: 2
  un-tagged-build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
