version: 2

defaults: &defaults

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.5.0
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

      - run:
          name: Avoid hosts unknown for github
          command: echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config


      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: cd xstate-to-svg && yarn run lint
      - run: cd xstate-to-svg && yarn run test:ci
      - run: cd xstate-to-svg && yarn run build

      - run: cd redux-saga-state-machine && yarn run lint
      - run: cd redux-saga-state-machine && yarn run test:ci
      - run: cd redux-saga-state-machine && yarn run build

      - run: cd example && yarn run lint
      - run: cd example && yarn run test:ci
      - run: cd example && yarn run build

      - run: yarn run junit-merge
      - store_test_results:
          path: ./junit.xml

      - run:
          name: Checking visualisations are up to date
          command: |
            if [[ $(git status --short) ]]; then
              echo "It looks like some visualisations are not up to date!"
              git status --short
              exit 1
            fi

      - run:
          name: Release to npm
          command: |
            if [[ $CIRCLE_BRANCH == 'fix-release' ]];
            then
              commit_message=$(git log --format=%s -n 1 $CIRCLE_SHA1)
              if [[ ! $commit_message =~ ^(v[0-9]+\.[0-9]+\.[0-9]+|no-deploy:.*)$ ]];
              then
                git config --global user.email "circleci@monket.net"
                git config --global user.name "circleci"

                yarn run publish
              fi
            fi
