version: 2

defaults: &defaults

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.5.0
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Authenticate with registry
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

      - run:
          name: Avoid unknown hosts error for github.com
          command: |
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config


      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn run build:ci
      - run: yarn run test:ci

      - store_test_results:
          path: ./junit.xml

      - run:
          name: Checking visualisations are up to date
          command: |
            if [[ $(git status --short) ]]; then
              echo "It looks like some visualisations are not up to date!"
              git status
              exit 1
            fi

      - run:
          name: Release to npm
          command: |
            if [[ $CIRCLE_BRANCH == 'master' ]];
            then
              commit_message=$(git log --format=%s -n 1 $CIRCLE_SHA1)
              if [[ ! $commit_message =~ ^(v[0-9]+\.[0-9]+\.[0-9]+|no-deploy:.*)$ ]];
              then
                echo 'Releasing to npm!'

                git config --global user.email "circleci@monket.net"
                git config --global user.name "circleci"

                npm run publish
              fi
            fi
